### ISSUE TITLE
Cross compiling

### ISSUE THREAD

**Issue by Treer** [nonunknown/gdextension-creator#3]
SConstruct is merging "host platform" and "target platform" together into "platform", so compiling for Windows on Linux doesn't work.

I don't expect you to debug this - it's fine when you're not cross-compiling, but do you know where the file originally came from so I can follow its history back through git?

I suspect it was a cut down version of a more complex SConstruct, and its lineage might help me add cross-compilation to mine since some of the more complicated ones in Godot have that and they all seem to be related, with blocks of common code.

**Comment by nonunknown** [comment]
you can just use: `scons platform=OS` where OS can be: `linux`, `windows`, `osx`

**Comment by Treer** [comment]
that's how it's supposed to work, but it doesn't, you get:
```
g++: error: unrecognized command line option ‘-std:c++17’; did you mean ‘-std=c++17’?
g++: error: unrecognized command line option ‘-W3’; did you mean ‘-W’?
g++: error: unrecognized command line option ‘-GR’; did you mean ‘-R’?
g++: error: unrecognized command line option ‘-EHsc’
g++: error: unrecognized command line option ‘-MDd’; did you mean ‘-MD’?
g++: error: unrecognized command line option ‘-ZI’; did you mean ‘-I’?
```

because `scons platform=windows` causes it to both target windows as well as to use windows-style formatting of the command line arguments, e.g. to use "-std:c++17" instead of "-std=c++17".

In the SConstruct file from godot-cpp (which looks closely related to this one)
* the host platform is `host_platform`
* the target platform is `env["platform"]`

And at line 170 [you can see it including the host platform in the decision of which argument formatting to use](https://github.com/godotengine/godot-cpp/blob/master/SConstruct#L170-L172=)

But in the SConstruct file for this project, on line 123 [it only uses the target platform to choose the argument format](https://github.com/nonunknown/gdextension-creator/blob/master/base/SConstruct#L123-L131=)

**Comment by nonunknown** [comment]
can you solve this? if so please do a PR!

**Comment by Treer** [comment]
do you know where the file originally came from so I can follow its history back through git?

**Comment by nonunknown** [comment]
this file someone gave me, and I dont remember if it was discord godot gdnative or godot rocket chat!

I think the best option in this case is using this one: https://github.com/godotengine/godot-cpp/blob/master/test/SConstruct
and the one above!

PS: the one you mentioned is for bindings, for the actual gdextension you must use the link I gave you now!
